### ISSUE TITLE
Save file not found

### ISSUE THREAD

**Issue by phixxy** [Andrew-Jayne/RPyG#4]
If there is no save file and the user types "load" the game currently exits. Maybe the main menu could be re-displayed to allow the creation of a save file without having to re-run the program.

**Comment by Andrew-Jayne** [comment]
Thanks for spotting that, fixed it here
https://github.com/Andrew-Jayne/RPyG/commit/47dfaccfc8fc7415608dec75a28091a9bfbb03c6

Thanks for the issues and PR's
